### ISSUE TITLE
Comment causes PHP notice

### ISSUE THREAD

**Issue by Remo** [ortic/css2less#9]
``` css
.text { position: relative; float: left; /*width: 320px;*/ } 
```

The code above causes an PHP notice:

> Notice: Undefined property: CssCommentToken::$MediaTypes in /var/remo/work/css2less/src/tokens/LessRuleList.php on line 118
